apiVersion: v2
name: prometheus
version: 1.0.0
dependencies:
- name: prometheus
  version: 27.44.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-postgres-exporter
  version: 7.3.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-operator-crds
  version: 24.0.1
  repository: https://prometheus-community.github.io/helm-charts
