apiVersion: v2
name: prometheus
version: 1.0.0
dependencies:
- name: prometheus
  version: 28.5.1
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-postgres-exporter
  version: 7.4.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-operator-crds
  version: 26.0.0
  repository: https://prometheus-community.github.io/helm-charts
