apiVersion: v2
name: prometheus
version: 1.0.0
dependencies:
- name: prometheus
  version: 28.9.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-postgres-exporter
  version: 7.5.0
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-operator-crds
  version: 27.0.0
  repository: https://prometheus-community.github.io/helm-charts
