image: ghcr.io/rommapp/romm:4.4.0
namespace: &namespace game-servers

host:
  subdomain: romm

secrets:
  primaryDomain:
    key: primaryDomain
    path: kv/data/domains
  homeDomain:
    key: homeDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/game-servers/romm
  volumes:
  - name: library
    subPath: library
    podPath: /romm/library
    type: DirectoryOrCreate
    readOnly: false
  - name: assets
    subPath: assets
    podPath: /romm/assets
    type: DirectoryOrCreate
    readOnly: false
  - name: config
    subPath: config
    podPath: /romm/config
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 8080
    externalPort: 8080
    protocol: TCP
