email: certificates@localhost
nameserver: "10.43.0.30:53"
namespace: &namespace core-services
caDuration: 43829h # 5 years

certificate:
  enabled: true

cert-manager:
  crds:
    enabled: true
  clusterResourceNamespace: *namespace
  namespace: *namespace