apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}-backup-job
  namespace: {{ .Values.vault.global.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.vault.global.namespace }}
  mount: kv
  type: kv-v2
  path: common/backblaze
  destination:
    name: {{ .Release.Name }}-backup-job
    create: true
    overwrite: true
