apiVersion: v2
name: valheim
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- name: valheim-discord-bot
  version: 1.4.1
  repository: https://floryn08.github.io/valheim-server-discord-bot