apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.crowdsec.namespaceOverride | default "core-services" }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.crowdsec.namespaceOverride | default "core-services" }}
  mount: kv
  type: kv-v2
  path: core-services/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}
    create: true
    overwrite: true
