apiVersion: v2
name: stirling-pdf
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: stirling-pdf-chart
    version: 2.2.0
    repository: https://docs.stirlingpdf.com/Stirling-PDF-chart