apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: {{ .Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.server }}
  source:
    path: {{ .Values.flaresolverr.path }}
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}