kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  WORLD_FILENAME: "The_Wary_Soup_of_Worries.wld"
  CONFIGPATH: "/config"
  CONFIG_FILENAME: "serverconfig.txt"
  LOGPATH: "/terraria-server/logs"
  WORLDPATH: "/root/.local/share/Terraria/Worlds"
