kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  PAPERLESS_ACCOUNT_DEFAULT_HTTP_PROTOCOL: http
  PAPERLESS_OCR_LANGUAGE: ron
  PAPERLESS_OCR_LANGUAGES: ron
  PAPERLESS_REDIS: redis://paperless-ngx-valkey.utility-services.svc
  PAPERLESS_TIME_ZONE: Europe/Bucharest
  USERMAP_GID: '1000'
  USERMAP_UID: '1000'
  PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect