apiVersion: v2
name: immich
version: 1.0.0
dependencies:
  - name: immich
    version: 0.10.3
    repository: https://immich-app.github.io/immich-charts
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 18.1.9