image: ghcr.io/mealie-recipes/mealie:v3.9.1
namespace: utility-services

host:
  subdomain: mealie

secrets:
  domain:
    key: primaryDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/utility-services/mealie
  volumes:
  - name: data
    subPath: data
    podPath: /app/data
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 9000
    externalPort: 9000
    protocol: TCP
  
