image: agregarr/agregarr:v2.3.0
namespace: media-management

host:
  subdomain: agregarr

secrets:
  domain:
    key: homeDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/media-management/agregarr
  volumes:
  - name: config
    subPath: config
    podPath: /app/config
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 7171
    externalPort: 7171
    protocol: TCP
