image: ghcr.io/requarks/wiki:2.5.311
namespace: utility-services

host:
  subdomain: wiki

secrets:
  domain:
    key: homeDomain
    path: kv/data/domains

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 3000
    externalPort: 3000
    protocol: TCP
  
