apiVersion: v2
name: homelab-alm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- name: homelab-alm
  version: 1.5.11
  repository: https://floryn08.github.io/homelab-alm