apiVersion: v2
name: paperless-ngx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: redis
  version: 23.2.6
  repository: https://charts.bitnami.com/bitnami