apiVersion: v2
name: paperless-ngx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: valkey
  version: 0.9.3
  repository: https://valkey-io.github.io/valkey-helm/