apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-oauth2
    create: true
    overwrite: true
    transformation:
      templates:
        SECURITY_OAUTH2_ISSUER:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/{{ .Release.Name }}/
        SECURITY_OAUTH2_CLIENTID:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientId") {{ "-}}" }}
        SECURITY_OAUTH2_CLIENTSECRET:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientSecret") {{ "-}}" }}
