kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: postgresql.core-services.svc
  DB_NAME: romm
  DB_USER: romm
  DB_PORT: "5432"
  ROMM_DB_DRIVER: postgresql
  HASHEOUS_API_ENABLED: "true"
  ROMM_PORT: "8080"
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "authentik"