apiVersion: v2
name: victoria-metrics
version: 1.0.0
dependencies:
- name: victoria-metrics-single
  version: 0.31.0
  repository: https://victoriametrics.github.io/helm-charts
- name: prometheus-node-exporter
  version: 4.51.1
  repository: https://prometheus-community.github.io/helm-charts
- name: kube-state-metrics
  version: 7.1.0
  repository: https://prometheus-community.github.io/helm-charts
